name: Deploy PHP Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Somee FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.4
        with:
          server: 192.52.242.121
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          server-dir: /www/TranTuanPhat.somee.com/
